pipeline:
  build:
    environment:
      - DOCKER_USERNAME=ukhomeofficedigital+drone
    image: quay.io/ukhomeofficedigital/drone-docker
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/scala-sbt-nodejs
    secrets: [ docker_password ]
    tags:
      - ${DRONE_COMMIT_SHA}
      - latest
    when:
      event: push

  build_tag:
    environment:
      - DOCKER_USERNAME=ukhomeofficedigital+drone
    image: quay.io/ukhomeofficedigital/drone-docker
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/scala-sbt-nodejs
    secrets: [ docker_password ]
    tags:
      - ${DRONE_TAG}
    when:
      event: tag
