---
kind: pipeline
type: kubernetes
name: docker-scala-sbt

platform:
  os: linux
  arch: amd64

steps:
  - build:
    environment:
      DOCKER_USERNAME: ukhomeofficedigital+drone
    image: quay.io/ukhomeofficedigital/drone-docker
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/scala-sbt
    secrets: [ docker_password ]
    tags:
      - ${DRONE_COMMIT_SHA}
      - latest
    when:
      event: push

  - build_tag:
    environment:
      DOCKER_USERNAME: ukhomeofficedigital+drone
    image: quay.io/ukhomeofficedigital/drone-docker
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/scala-sbt
    secrets: [ docker_password ]
    tags:
      - ${DRONE_TAG}
    when:
      event: tag
