kind: pipeline
type: kubernetes
name: scala-sbt

platform:
  os: linux
  arch: amd64

steps:
  - name: ecr-login
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/dind-awscli:19.03.12-dind-1.18.55
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
    commands:
      # wait for docker service to be up before running docker build
      - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
      - aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 340268328991.dkr.ecr.eu-west-2.amazonaws.com
    volumes:
      - name: dockerclientconfig
        path: /root/.docker
    when:
      event:
        - push

  - name: build_images
    pull: if-not-exists
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
    environment:
      AWS_REGION: eu-west-2
    commands:
      - docker build -t 340268328991.dkr.ecr.eu-west-2.amazonaws.com/rtge/scala-sbt-8jre:$${DRONE_COMMIT_SHA} . --no-cache -f Dockerfile-8jre
      - docker build -t 340268328991.dkr.ecr.eu-west-2.amazonaws.com/rtge/scala-sbt-11jre:$${DRONE_COMMIT_SHA} . --no-cache -f Dockerfile-11jre
      - docker build -t 340268328991.dkr.ecr.eu-west-2.amazonaws.com/rtge/scala-sbt-17jre:$${DRONE_COMMIT_SHA} . --no-cache -f Dockerfile-17jre
      - docker push scala-sbt-8jre:$${DRONE_COMMIT_SHA}
      - docker push scala-sbt-11jre:$${DRONE_COMMIT_SHA}
      - docker push scala-sbt-17jre:$${DRONE_COMMIT_SHA}
    volumes:
      - name: dockerclientconfig
        path: /root/.docker
    depends_on:
      - ecr-login
    when:
      event:
        - push
        - tag

          #- name: push_build_image
          #  image: plugins/ecr
          #  settings:
          #    registry: 340268328991.dkr.ecr.eu-west-2.amazonaws.com
          #    repo: evw/elastic-sync
          #    access_key:
          #      from_secret: AWS_ACCESS_KEY_ID
          #    secret_key:
          #      from_secret: AWS_SECRET_ACCESS_KEY
          #    tags:
          #      - ${DRONE_COMMIT_SHA}
          #      - latest
          #  environment:
          #    AWS_REGION: eu-west-2
          #  when:
          #    event:
          #      - push
          #  depends_on:
          #    - build_image

services:
- name: docker
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind

volumes:
  - name: dockerclientconfig
    temp: {}

