#!/bin/bash

case $1 in 

  "8")
    export JAVA_HOME=/etc/alternatives/jre_1.8.0_openjdk/
    ;;
  "11") 
    export JAVA_HOME=/etc/alternatives/jre_11_openjdk/
    ;;
  "17") 
    export JAVA_HOME=/etc/alternatives/jre_17_openjdk/
    ;;
esac

export JRE_HOME=$JAVA_HOME/jre
export PATH=$JAVA_HOME/bin:$PATH
